### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by drjwbaker** [data-lessons/library-data-intro#18]
So I tried to add @ccronje as an admin for this repo and in my fiddling about can no longer see the 'settings' button. Can someone fix please? (cc @mkuzak @weaverbel) Sorry :(

**Comment by weaverbel** [comment]
@drjwbaker I have made you a team maintainer - does that help?

**Comment by weaverbel** [comment]
@drjwbaker I'll ask Tracy to add @ccronje 

@tracykteal Can you please add @ccronje as an admin on data-lessons/library-data-intro

Ta
Belinda

**Comment by drjwbaker** [comment]
@weaverbel Hmm no. On https://github.com/orgs/data-lessons/teams/library/repositories next to 'data-lessons / library-data-intro' it reads 'Write' rather than 'Admin'. This appears to be something I changed in error...

**Comment by weaverbel** [comment]
@tracykteal Sorry but we have a problem now on one of the repos when James changed a setting - *this* problem:

"On https://github.com/orgs/data-lessons/teams/library/repositories next to 'data-lessons / library-data-intro' it reads 'Write' rather than 'Admin'. "

I can't see how to fix it. Can you as the Owner? The only option is to remove which would be drastic !

**Comment by drjwbaker** [comment]
Sorry :( (this is up there with that time I removed myself as administrator for my own blog of which I was the only administrator..)

**Comment by tracykteal** [comment]
It's not you! I'm still trying to figure out the new github teams/permissions too. I added @ccronje to the team and set permissions back to Admin. Let me know if that works OK.

**Comment by ccronje** [comment]
Thanks all, I'm in :-)

**Comment by drjwbaker** [comment]
I can see the settings again!
