### ISSUE TITLE
delimiters in colour example

### ISSUE THREAD

**Issue by ccronje** [data-lessons/library-data-intro#2]
The colour insensitive example `/regex/i` tripped me up a little. I wonder if it's worth adding a note earlier that delimiters are `/regex/` which is case sensitive (as can be seen in [https://regex101.com/](https://regex101.com/) - but have been removed from examples for easier reading.

**Comment by weaverbel** [comment]
@ccronje I don't know enough about regex to comment here - @drjwbaker might have a view.

**Comment by drjwbaker** [comment]
I can take this as a thing to normalise.

**Comment by drjwbaker** [comment]
Okay. I see what you mean. That was a late hack: I recall someone searched online and found this answer and I threw it in. I'd made a note about delimiters earlier on in the lesson (in addition to our intention to ignore them, mostly) then added this text in as the answer to the colour problem:

In real life, you *should* only come across the case insensitive variations `colour`, `color`, `Colour`, `Color`, `COLOUR`, and `COLOR` (rather than, say, `coLour`. So one option would be `\b[Cc]olou?r\b|\bCOLOU?R\b`. This can, however, get quickly quite complex. An option we've not discussed is to take advantage of the `/` delimiters and add an ignore case flag: so `/colou?r/i` will match all case insensitive variants of `colour` and `color`.
