### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ccronje** [data-lessons/library-data-intro#9]
@weaverbel The license James applied is CC BY-SA, which requires us to apply the same license. Data Carpentry uses CC BY. Will this be an issue with DC in terms of consistency?

**Comment by drjwbaker** [comment]
Don't know. I prefer SA but am happy to acknowledge consent to move to CC BY for the sake of consistency/integration. Most of the content is of my own creation for this lesson, and those that are reworked - see https://github.com/data-lessons/library-data-intro/blob/master/lesson-materials/LibCarp-introtodata.md#references - are from CC BY source material.

**Comment by weaverbel** [comment]
@drjwbaker @ccronje CC-BY definitely most open licence so it is preferred. The problem with adding SA is that people may use and NOT share and then how would we police that and would we even want to? Main thing (imo) is to acknowledge James, Owen et al and all the hard work they've done to get to the point where others can work on it and CC-BY gives us that.

**Comment by drjwbaker** [comment]
CC BY is fine. I hereby wave the SA on the original LibCarp lessons (expect in those cases where the content came from differently licensed sources as noted in the original readmes)

Slight OT: as a general point on SA, SA does not preclude sharing so long as it is shared with the same terms, SA. A number of authors prefer it because it ensures that their openly released content stays open even when it is derived. See https://figshare.com/articles/Guide_to_Creative_Commons_for_Humanities_and_Social_Science_Monograph_Authors_OAPENUK_2013_/928467

**Comment by drjwbaker** [comment]
Can we close this now?

**Comment by weaverbel** [comment]
Yes, I think so @drjwbaker
